### ISSUE TITLE
Using easyXDM from chrome and firefox extension.

### ISSUE THREAD

**Issue by nullrocket** [oyvindkinsey/easyXDM#224]
In order to use easyXDM from browser addons in chrome and firefox you have to modify the URI regex from this:

``` javascript
var reURI = /^((http.?:)\/\/([^:\/\s]+)(:\d+)*)/; // returns groups for protocol (2), domain (3) and port (4) 


```

to this:

``` javascript
var reURI = /^((http.?:|chrome-extension.?:|resource.?:)\/\/([^:\/\s]+)(:\d+)*)/; // returns groups for protocol (2), domain (3) and port (4)


```

It may be useful to others to implement these changes.

**Comment by lievenjanssen** [comment]
@oyvindkinsey some chrome extensions are automatically added to all web pages in Chrome (e.g. Buffer) If a chrome extension is added easyXDM calls the getLocation function for the extension url, the url match returns null and the next line triggers an error:

```
var m = url.toLowerCase().match(reURI);
var proto = m[2], domain = m[3], port = m[4] || "";
```

![image](https://cloud.githubusercontent.com/assets/958643/13048840/f1070f0e-d3e8-11e5-9145-1865795ada39.png)

**Comment by oyvindkinsey** [comment]
@lievenjanssen I'm not sure I follow - when would `getLocation` be called? 
Are you perhaps referring to https://github.com/oyvindkinsey/easyXDM/blob/master/src/stack/PostMessageTransport.js#L55 which operates on incoming messages?

If you want to put up a patch for this case, I'd be happy to accept it, but this project isn't being actively developed at this time.

**Comment by AdriVanHoudt** [comment]
As a reference this was fixed by https://github.com/oyvindkinsey/easyXDM/commit/d39ebe84358c222c5b9926fef68d59fed5c39b60
