### ISSUE TITLE
when is a lazy iframe ready?

### ISSUE THREAD

**Issue by wzrd-clss** [oyvindkinsey/easyXDM#268]
is there a  ready callback for lazy loaded iframes? onReady is not fired when lazy is set to true

**Comment by oyvindkinsey** [comment]
Sorry for not looking at this - what turned out to be the issue?

**Comment by wzrd-clss** [comment]
Im not sure. I updated to the latest version a couple days ago and just decided to try using the onReady function again today and it worked. the problem could have been an old version or bad configuration
