### ISSUE TITLE
Simple instructions, please!

### ISSUE THREAD

**Issue by alvaro1728** [oyvindkinsey/easyXDM#270]
Hi,  I'm trying to accomplish two simple tasks:

1. Send GET request to a remote API (out of my control) and read back JSON response.
2. Send POST request with JSON data to a remote API and read back JSON response.

These two may be done multiple times during the lifetime of my page.  

I've read the README but I'm not sure what the exact instructions are for accomplishing this, starting with: which source files do I need to include in my project?

Thanks!
Alvaro

**Comment by oyvindkinsey** [comment]
This is better suited for the the discussion group (https://groups.google.com/forum/#!forum/easyxdm) although this is also covered in the documentation (http://easyxdm.net/wp/2010/03/17/cross-domain-ajax/) and examples (https://github.com/oyvindkinsey/easyXDM/blob/master/src/example/xhr.html).

**Comment by oyvindkinsey** [comment]
> .. (out of my control) 

This precludes use of easyXDM though, since it requires the remote party to provide an easyXDM host.
