### ISSUE TITLE
Provider and Consumer Examples not working.

### ISSUE THREAD

**Issue by kraigmustard** [oyvindkinsey/easyXDM#285]
Does anyone know why you get this error

Uncaught Error: url is undefined or empty
    at resolveUrl (Core.js:328)

on the provider script, when in the docs, you don't need to define a URL. I'm confused.

**Comment by oyvindkinsey** [comment]
There's not enough information here to help. 
But this could happen if you're loading the provider directly instead of letting easyXDM do it for you.
