### ISSUE TITLE
url is undefined or null inside `resolveUrl(url)`

### ISSUE THREAD

**Issue by millermedeiros** [oyvindkinsey/easyXDM#31]
Just downloaded easyXDM-2.4.7.99 - and created a simple socket based on the example showed on the documentation just changing the location of the "name.html" for some reason I get an error inside the function `resolveUrl` since `url` is null.

quick fix:

url = (url)? url.replace(reDoubleSlash, "$1/") : '';

**Comment by andreas83** [comment]
I had the same issue while initializing easyXDM while being not inside an iframe... 
I fixed it with the following if statement (check if inside iframe)

           
```
//check if inside iframe
if ( window.location !== window.parent.location ) {
     var socket = new easyXDM.Socket({
          onReady:  function(){
               socket.postMessage(document.body.scrollHeight)
          }
     });
}
```
